### ISSUE TITLE
[Question] Why does it resolves domain to IP?

### ISSUE THREAD

**Issue by bergziege** [matrix-org/fed-tester-ui#36]
Hi,

just experimenting with my first matrix server (synapse) and trying to set up federation.
For that I port forwarded 8443 to my synapse and also having a cert for my domain. So when I call it via browser everything is fine.
When I now use the tester the domain gets resolved to IP which then (at least when manually calling) throws an cert error (because the cert is for the domain, not the ip) and fails.

Why does the tester resolves to IP and does not make the call with the given domain?

Cheers
debgz

**Comment by richvdh** [comment]
> Why does it resolves domain to IP

because the internet works over IP, not directly via hostnames?

Perhaps you could give more details about the problem you are seeing. Please provide an example hostname where you are seeing the problem.

**Comment by richvdh** [comment]
closing this for now

**Comment by erinarbleizez** [comment]
I reopen this ticket because I think I know what OP is facing as I am trying to migrate my matrix server to IPv6 only. here is the case:

![Capture d’écran du 2023-03-30 10-47-08](https://user-images.githubusercontent.com/10438112/228781767-aad67037-fd06-4c76-b71f-3689002d2891.png)

why trying to access through https to the ip instead of the domain (matrix.sidh.bzh) to access the server key? https certificat can be issue over an IP but is highly not recommended

**Comment by richvdh** [comment]
> why trying to access through https to the ip instead of the domain

You are misunderstanding the error message. It is not looking for a certificate for the IP address; it is just saying that a TLS error occurred with a connection to that IP address.

The problem here is a misconfiguration on your server, but this is not a support forum. The use of SRV records is not recommended and is likely what is tripping you up here.

**Comment by ColonelThirtyTwo** [comment]
IMO it's a bit confusing. TLS certificates mean that the origin is important, so the fact that the validator hints that it tries to access the server via an IP address with no domain name raises a red flag to anyone using it that the tool may not be testing the TLS aspect correctly, even if it internally it uses the domain name.

**Comment by richvdh** [comment]
> IMO it's a bit confusing. TLS certificates mean that the origin is important, so the fact that the validator hints that it tries to access the server via an IP address with no domain name raises a red flag to anyone using it that the tool may not be testing the TLS aspect correctly, even if it internally it uses the domain name.

I agree, the error could be clearer. Pull requests to improve it would be welcome :)
